### ISSUE TITLE
reload_time effects/bonuses not being applied?

### ISSUE THREAD

**Issue by ToucheSir** [gbts/aoe2calc#1]
First off, just wanted to say that this project is great! Elm seems to fit extremely well here.

One thing I noticed from trying out techs such as thumb ring is that Rate of Fire bonuses don't seem to be applying in the unit or arena views. This also applies civ-inherent RoF bonuses (e.g. Ethiopians). Digging around in the data, it seems that effects of this nature modify the `reloading_time` attribute rather than the `reload_time`, and thus all such modifications are just silently ignored/discarded. Not sure if this is something that can be changed in the import script or must be handled as a special case by the application, but it would be wonderful to have RoF bonuses visible as well.

**Comment by gbts** [comment]
Good catch, I updated the JSON files and it seems to be working properly now.
